version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brief_nest_services
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db  # On force l'hôte sur le nom du service Docker
    depends_on:
      - db

volumes:
  db-data: